name: Initial Design CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows the action to be run manually from GitHub UI

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./driven-outcomes-playground
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./driven-outcomes-playground
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/tbysctt/driven-outcomes-initial-design:latest
            ghcr.io/tbysctt/driven-outcomes-initial-design:${{ github.sha }}

